name: Build and Zip Firefox Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          set -euxo pipefail
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: |
          set -euxo pipefail
          pnpm install

      - name: Build Firefox
        run: |
          set -euxo pipefail
          pnpm build:firefox

      - name: Zip Firefox extension
        run: |
          set -euxo pipefail
          test -d dist_firefox
          zip -r firefox-extension.zip dist_firefox

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-chat-boost-firefox
          path: firefox-extension.zip
